# Generated by Django 3.2 on 2021-05-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
